# Generated by Django 5.0.6 on 2024-05-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Data',
        ),
    ]
